# Import configuration from Config Server
#spring.config.import=configserver:http://localhost:8071/

spring.config.import=configserver:http://configserver:8071/

# Application name
spring.application.name=account

# Active profile
spring.profiles.active=dev

# Database configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/account_service
#spring.datasource.username=account
#spring.datasource.password=account@168

# Hibernate configuration
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update

#Temporary Database
spring.datasource.url=jdbc:h2:mem:h2db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=soda
spring.datasource.password=soda
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Server port
server.port=8080

management.endpoints.web.exposure.include=*