version: "3.8"
services:
  configserver:
    image: kroessoda/config_server:latest
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - sodanetwork
      
  mongodb:
    image: mvertes/alpine-mongo:latest
    ports:
      - "7777:27017"
    networks:
      - sodanetwork

  eurekaserver:
    image: kroessoda/eureka_server:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - sodanetwork
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "http://configserver:8000/"

  account:
    image: kroessoda/account:latest
    mem_limit: 700m
    ports:
      - "7000:7000"
    networks:
      - sodanetwork
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "http://configserver:8000/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:9000/eureka/"

  loan:
    image: kroessoda/loan:latest
    mem_limit: 700m
    ports:
      - "6000:6000"
    networks:
      - sodanetwork
    depends_on:
      - configserver
      - eurekaserver
      - mongodb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "http://configserver:8000/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:9000/"
      MONGODB_HOST_NAME: mongodb

  card:
    image: kroessoda/card:latest
    mem_limit: 700m
    ports:
      - "5000:5000"
    networks:
      - sodanetwork
    depends_on:
      - configserver
      - eurekaserver
      - mongodb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "http://configserver:8000/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:9000/"
      MONGODB_HOST_NAME: mongodb

networks:
  sodanetwork: